# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8d4b9a29228370e361f4dfb25a502ce27e6e1a44f756ee2af2d7e67955889c94abf81824af5c5c85596c6683c5e05a4d92f0b04602e5223d8e496ec49efd42f

test:
  secret_key_base: 75024308e6b8d6f8e630de660b1a92e9e91bd6c154420a670afc49d29d0fafd13092d99b397e6b8b5362bbb317301e1bb9eadc96cbe5824f8961608a722d52f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
